services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot

  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   restart: unless-stopped
  #   ports:
  #     - 6382:6379

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lab88_db
      MYSQL_USER: lab88_admin
      MYSQL_PASSWORD: 3v0lv3ADM!N
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    container_name: app
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - $PWD/:/var/www/
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - /var/sftp:/var/sftp
    depends_on:
      - mysql

  # supervisor:
  #   container_name: supervisor
  #   image: evolveindustries/lab88:5.0.1
  #   restart: unless-stopped
  #   command: "supervisord"
  #   volumes:
  #     - ./:/var/www/
  #     - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

volumes:
  mysql_data:

networks:
  default:
    name: app-network
